services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=db
      - DB_USER=db_admin
      - DB_PASS=admin

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: stilix09@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"