# Generated by Django 3.2.16 on 2023-01-24 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка')),
                ('user_h', models.IntegerField(default=0, verbose_name='Часов в игре')),
                ('user_review', models.TextField(blank=True, verbose_name='Отзыв')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.profile', verbose_name='Пользователь')),
                ('games', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.game', verbose_name='Игра')),
            ],
        ),
        migrations.DeleteModel(
            name='UserGameMenu',
        ),
    ]
