# Generated by Django 3.2.16 on 2023-01-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20230128_2201'),
        ('client', '0003_auto_20230128_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='steamgames',
            field=models.ManyToManyField(to='games.SteamGames'),
        ),
    ]
