# Generated by Django 3.2.16 on 2023-02-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_profile_steamgames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='games',
        ),
        migrations.RemoveField(
            model_name='usergamem',
            name='games',
        ),
    ]
