# Generated by Django 3.2.16 on 2023-01-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_steamgames_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamgames',
            name='appid',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='steamgames',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
